### ISSUE TITLE
Homepage link on PyPI points to bitbucket.

### ISSUE THREAD

**Issue by jsbronder** [cmcqueen/cobs-python#2]
I'd file a PR, but it looks like PyPI isn't pulling from setup.py and has its own metadata.  The homepage link is pointing to http://bitbucket.org/cmcqueen1975/cobs-python/ rather then here.

https://pypi.org/project/cobs/

**Comment by cmcqueen** [comment]
It's something I'd updated in `setup.py` a while ago. But I hadn't done a release since then that includes the updated metadata.

I've made a release of v1.2.0 today which updates the homepage link.
